apiVersion: v1
kind: Service
metadata:
  name: {{ include "xrd-conversion-operator.fullname" . }}-manager-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "xrd-conversion-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  selector:
    {{- include "xrd-conversion-operator.managerSelectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
{{- if .Values.manager.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "xrd-conversion-operator.fullname" . }}-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "xrd-conversion-operator.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.manager.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "xrd-conversion-operator.managerSelectorLabels" . | nindent 6 }}
{{- end }}
