//go:build !ignore_autogenerated

/*
Copyright 2026 The declarative-conversion-operator Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArrayToMapByKeyParams) DeepCopyInto(out *ArrayToMapByKeyParams) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArrayToMapByKeyParams.
func (in *ArrayToMapByKeyParams) DeepCopy() *ArrayToMapByKeyParams {
	if in == nil {
		return nil
	}
	out := new(ArrayToMapByKeyParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssignedConfigRef) DeepCopyInto(out *AssignedConfigRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssignedConfigRef.
func (in *AssignedConfigRef) DeepCopy() *AssignedConfigRef {
	if in == nil {
		return nil
	}
	out := new(AssignedConfigRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingSpec) DeepCopyInto(out *AutoscalingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingSpec.
func (in *AutoscalingSpec) DeepCopy() *AutoscalingSpec {
	if in == nil {
		return nil
	}
	out := new(AutoscalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CRDConversionConfig) DeepCopyInto(out *CRDConversionConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CRDConversionConfig.
func (in *CRDConversionConfig) DeepCopy() *CRDConversionConfig {
	if in == nil {
		return nil
	}
	out := new(CRDConversionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CRDConversionConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CRDConversionConfigList) DeepCopyInto(out *CRDConversionConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CRDConversionConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CRDConversionConfigList.
func (in *CRDConversionConfigList) DeepCopy() *CRDConversionConfigList {
	if in == nil {
		return nil
	}
	out := new(CRDConversionConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CRDConversionConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CRDConversionConfigSpec) DeepCopyInto(out *CRDConversionConfigSpec) {
	*out = *in
	out.TargetCRD = in.TargetCRD
	if in.Spokes != nil {
		in, out := &in.Spokes, &out.Spokes
		*out = make([]SpokeVersionRules, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.WebhookServerRef != nil {
		in, out := &in.WebhookServerRef, &out.WebhookServerRef
		*out = new(WebhookServerRef)
		**out = **in
	}
	if in.ConversionReviewVersions != nil {
		in, out := &in.ConversionReviewVersions, &out.ConversionReviewVersions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CRDConversionConfigSpec.
func (in *CRDConversionConfigSpec) DeepCopy() *CRDConversionConfigSpec {
	if in == nil {
		return nil
	}
	out := new(CRDConversionConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CRDConversionConfigStatus) DeepCopyInto(out *CRDConversionConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SpokeStatuses != nil {
		in, out := &in.SpokeStatuses, &out.SpokeStatuses
		*out = make([]SpokeConversionStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CRDConversionConfigStatus.
func (in *CRDConversionConfigStatus) DeepCopy() *CRDConversionConfigStatus {
	if in == nil {
		return nil
	}
	out := new(CRDConversionConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateIssuerRef) DeepCopyInto(out *CertificateIssuerRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateIssuerRef.
func (in *CertificateIssuerRef) DeepCopy() *CertificateIssuerRef {
	if in == nil {
		return nil
	}
	out := new(CertificateIssuerRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateSpec) DeepCopyInto(out *CertificateSpec) {
	*out = *in
	out.IssuerRef = in.IssuerRef
	if in.DNSNames != nil {
		in, out := &in.DNSNames, &out.DNSNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.RenewBefore != nil {
		in, out := &in.RenewBefore, &out.RenewBefore
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateSpec.
func (in *CertificateSpec) DeepCopy() *CertificateSpec {
	if in == nil {
		return nil
	}
	out := new(CertificateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConstantParams) DeepCopyInto(out *ConstantParams) {
	*out = *in
	in.Value.DeepCopyInto(&out.Value)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConstantParams.
func (in *ConstantParams) DeepCopy() *ConstantParams {
	if in == nil {
		return nil
	}
	out := new(ConstantParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConversionRule) DeepCopyInto(out *ConversionRule) {
	*out = *in
	if in.FieldRename != nil {
		in, out := &in.FieldRename, &out.FieldRename
		*out = new(FieldRenameParams)
		**out = **in
	}
	if in.ScalarToObject != nil {
		in, out := &in.ScalarToObject, &out.ScalarToObject
		*out = new(ScalarToObjectParams)
		(*in).DeepCopyInto(*out)
	}
	if in.ObjectToScalar != nil {
		in, out := &in.ObjectToScalar, &out.ObjectToScalar
		*out = new(ObjectToScalarParams)
		(*in).DeepCopyInto(*out)
	}
	if in.SingletonArrayToObject != nil {
		in, out := &in.SingletonArrayToObject, &out.SingletonArrayToObject
		*out = new(SingletonArrayToObjectParams)
		**out = **in
	}
	if in.ObjectToSingletonArray != nil {
		in, out := &in.ObjectToSingletonArray, &out.ObjectToSingletonArray
		*out = new(ObjectToSingletonArrayParams)
		**out = **in
	}
	if in.FieldsToMap != nil {
		in, out := &in.FieldsToMap, &out.FieldsToMap
		*out = new(FieldsToMapParams)
		(*in).DeepCopyInto(*out)
	}
	if in.MapToFields != nil {
		in, out := &in.MapToFields, &out.MapToFields
		*out = new(MapToFieldsParams)
		(*in).DeepCopyInto(*out)
	}
	if in.ToAnnotation != nil {
		in, out := &in.ToAnnotation, &out.ToAnnotation
		*out = new(ToMetadataParams)
		**out = **in
	}
	if in.ToLabel != nil {
		in, out := &in.ToLabel, &out.ToLabel
		*out = new(ToMetadataParams)
		**out = **in
	}
	if in.EnumRemap != nil {
		in, out := &in.EnumRemap, &out.EnumRemap
		*out = new(EnumRemapParams)
		(*in).DeepCopyInto(*out)
	}
	if in.DefaultValue != nil {
		in, out := &in.DefaultValue, &out.DefaultValue
		*out = new(DefaultValueParams)
		(*in).DeepCopyInto(*out)
	}
	if in.Constant != nil {
		in, out := &in.Constant, &out.Constant
		*out = new(ConstantParams)
		(*in).DeepCopyInto(*out)
	}
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = new(DeleteParams)
		**out = **in
	}
	if in.JSONPatch != nil {
		in, out := &in.JSONPatch, &out.JSONPatch
		*out = new(JSONPatchParams)
		(*in).DeepCopyInto(*out)
	}
	if in.ForEach != nil {
		in, out := &in.ForEach, &out.ForEach
		*out = new(ForEachParams)
		(*in).DeepCopyInto(*out)
	}
	if in.TypeCoerce != nil {
		in, out := &in.TypeCoerce, &out.TypeCoerce
		*out = new(TypeCoerceParams)
		**out = **in
	}
	if in.ScalarToFields != nil {
		in, out := &in.ScalarToFields, &out.ScalarToFields
		*out = new(ScalarToFieldsParams)
		(*in).DeepCopyInto(*out)
	}
	if in.FieldsToScalar != nil {
		in, out := &in.FieldsToScalar, &out.FieldsToScalar
		*out = new(FieldsToScalarParams)
		(*in).DeepCopyInto(*out)
	}
	if in.ArrayToMapByKey != nil {
		in, out := &in.ArrayToMapByKey, &out.ArrayToMapByKey
		*out = new(ArrayToMapByKeyParams)
		**out = **in
	}
	if in.MapToArrayByKey != nil {
		in, out := &in.MapToArrayByKey, &out.MapToArrayByKey
		*out = new(MapToArrayByKeyParams)
		**out = **in
	}
	if in.NumericScale != nil {
		in, out := &in.NumericScale, &out.NumericScale
		*out = new(NumericScaleParams)
		**out = **in
	}
	if in.ListJoin != nil {
		in, out := &in.ListJoin, &out.ListJoin
		*out = new(ListJoinParams)
		**out = **in
	}
	if in.ListSplit != nil {
		in, out := &in.ListSplit, &out.ListSplit
		*out = new(ListSplitParams)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConversionRule.
func (in *ConversionRule) DeepCopy() *ConversionRule {
	if in == nil {
		return nil
	}
	out := new(ConversionRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConversionWebhookServer) DeepCopyInto(out *ConversionWebhookServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConversionWebhookServer.
func (in *ConversionWebhookServer) DeepCopy() *ConversionWebhookServer {
	if in == nil {
		return nil
	}
	out := new(ConversionWebhookServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConversionWebhookServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConversionWebhookServerList) DeepCopyInto(out *ConversionWebhookServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConversionWebhookServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConversionWebhookServerList.
func (in *ConversionWebhookServerList) DeepCopy() *ConversionWebhookServerList {
	if in == nil {
		return nil
	}
	out := new(ConversionWebhookServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConversionWebhookServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConversionWebhookServerSpec) DeepCopyInto(out *ConversionWebhookServerSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(AutoscalingSpec)
		**out = **in
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(ImageSpec)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	in.Certificate.DeepCopyInto(&out.Certificate)
	in.Service.DeepCopyInto(&out.Service)
	if in.PodDisruptionBudget != nil {
		in, out := &in.PodDisruptionBudget, &out.PodDisruptionBudget
		*out = new(PodDisruptionBudgetSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConversionWebhookServerSpec.
func (in *ConversionWebhookServerSpec) DeepCopy() *ConversionWebhookServerSpec {
	if in == nil {
		return nil
	}
	out := new(ConversionWebhookServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConversionWebhookServerStatus) DeepCopyInto(out *ConversionWebhookServerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AssignedConfigs != nil {
		in, out := &in.AssignedConfigs, &out.AssignedConfigs
		*out = make([]AssignedConfigRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConversionWebhookServerStatus.
func (in *ConversionWebhookServerStatus) DeepCopy() *ConversionWebhookServerStatus {
	if in == nil {
		return nil
	}
	out := new(ConversionWebhookServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultValueParams) DeepCopyInto(out *DefaultValueParams) {
	*out = *in
	in.Default.DeepCopyInto(&out.Default)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultValueParams.
func (in *DefaultValueParams) DeepCopy() *DefaultValueParams {
	if in == nil {
		return nil
	}
	out := new(DefaultValueParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteParams) DeepCopyInto(out *DeleteParams) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteParams.
func (in *DeleteParams) DeepCopy() *DeleteParams {
	if in == nil {
		return nil
	}
	out := new(DeleteParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnumRemapParams) DeepCopyInto(out *EnumRemapParams) {
	*out = *in
	if in.Mapping != nil {
		in, out := &in.Mapping, &out.Mapping
		*out = make([]EnumValueMapping, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnumRemapParams.
func (in *EnumRemapParams) DeepCopy() *EnumRemapParams {
	if in == nil {
		return nil
	}
	out := new(EnumRemapParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnumValueMapping) DeepCopyInto(out *EnumValueMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnumValueMapping.
func (in *EnumValueMapping) DeepCopy() *EnumValueMapping {
	if in == nil {
		return nil
	}
	out := new(EnumValueMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldRenameParams) DeepCopyInto(out *FieldRenameParams) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldRenameParams.
func (in *FieldRenameParams) DeepCopy() *FieldRenameParams {
	if in == nil {
		return nil
	}
	out := new(FieldRenameParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldsToMapParams) DeepCopyInto(out *FieldsToMapParams) {
	*out = *in
	if in.HubPaths != nil {
		in, out := &in.HubPaths, &out.HubPaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.KeyNames != nil {
		in, out := &in.KeyNames, &out.KeyNames
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldsToMapParams.
func (in *FieldsToMapParams) DeepCopy() *FieldsToMapParams {
	if in == nil {
		return nil
	}
	out := new(FieldsToMapParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldsToScalarParams) DeepCopyInto(out *FieldsToScalarParams) {
	*out = *in
	if in.HubFields != nil {
		in, out := &in.HubFields, &out.HubFields
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldsToScalarParams.
func (in *FieldsToScalarParams) DeepCopy() *FieldsToScalarParams {
	if in == nil {
		return nil
	}
	out := new(FieldsToScalarParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForEachParams) DeepCopyInto(out *ForEachParams) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]ConversionRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForEachParams.
func (in *ForEachParams) DeepCopy() *ForEachParams {
	if in == nil {
		return nil
	}
	out := new(ForEachParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSpec) DeepCopyInto(out *ImageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSpec.
func (in *ImageSpec) DeepCopy() *ImageSpec {
	if in == nil {
		return nil
	}
	out := new(ImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JSONPatchOp) DeepCopyInto(out *JSONPatchOp) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JSONPatchOp.
func (in *JSONPatchOp) DeepCopy() *JSONPatchOp {
	if in == nil {
		return nil
	}
	out := new(JSONPatchOp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JSONPatchParams) DeepCopyInto(out *JSONPatchParams) {
	*out = *in
	if in.HubToSpoke != nil {
		in, out := &in.HubToSpoke, &out.HubToSpoke
		*out = make([]JSONPatchOp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SpokeToHub != nil {
		in, out := &in.SpokeToHub, &out.SpokeToHub
		*out = make([]JSONPatchOp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JSONPatchParams.
func (in *JSONPatchParams) DeepCopy() *JSONPatchParams {
	if in == nil {
		return nil
	}
	out := new(JSONPatchParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListJoinParams) DeepCopyInto(out *ListJoinParams) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListJoinParams.
func (in *ListJoinParams) DeepCopy() *ListJoinParams {
	if in == nil {
		return nil
	}
	out := new(ListJoinParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListSplitParams) DeepCopyInto(out *ListSplitParams) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListSplitParams.
func (in *ListSplitParams) DeepCopy() *ListSplitParams {
	if in == nil {
		return nil
	}
	out := new(ListSplitParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LosslessVerdict) DeepCopyInto(out *LosslessVerdict) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LosslessVerdict.
func (in *LosslessVerdict) DeepCopy() *LosslessVerdict {
	if in == nil {
		return nil
	}
	out := new(LosslessVerdict)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MapToArrayByKeyParams) DeepCopyInto(out *MapToArrayByKeyParams) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MapToArrayByKeyParams.
func (in *MapToArrayByKeyParams) DeepCopy() *MapToArrayByKeyParams {
	if in == nil {
		return nil
	}
	out := new(MapToArrayByKeyParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MapToFieldsParams) DeepCopyInto(out *MapToFieldsParams) {
	*out = *in
	if in.SpokePaths != nil {
		in, out := &in.SpokePaths, &out.SpokePaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.KeyNames != nil {
		in, out := &in.KeyNames, &out.KeyNames
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MapToFieldsParams.
func (in *MapToFieldsParams) DeepCopy() *MapToFieldsParams {
	if in == nil {
		return nil
	}
	out := new(MapToFieldsParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NumericScaleParams) DeepCopyInto(out *NumericScaleParams) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NumericScaleParams.
func (in *NumericScaleParams) DeepCopy() *NumericScaleParams {
	if in == nil {
		return nil
	}
	out := new(NumericScaleParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectToScalarParams) DeepCopyInto(out *ObjectToScalarParams) {
	*out = *in
	if in.DefaultsForOtherKeys != nil {
		in, out := &in.DefaultsForOtherKeys, &out.DefaultsForOtherKeys
		*out = make(map[string]apiextensionsv1.JSON, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectToScalarParams.
func (in *ObjectToScalarParams) DeepCopy() *ObjectToScalarParams {
	if in == nil {
		return nil
	}
	out := new(ObjectToScalarParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectToSingletonArrayParams) DeepCopyInto(out *ObjectToSingletonArrayParams) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectToSingletonArrayParams.
func (in *ObjectToSingletonArrayParams) DeepCopy() *ObjectToSingletonArrayParams {
	if in == nil {
		return nil
	}
	out := new(ObjectToSingletonArrayParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodDisruptionBudgetSpec) DeepCopyInto(out *PodDisruptionBudgetSpec) {
	*out = *in
	if in.MinAvailable != nil {
		in, out := &in.MinAvailable, &out.MinAvailable
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.MaxUnavailable != nil {
		in, out := &in.MaxUnavailable, &out.MaxUnavailable
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodDisruptionBudgetSpec.
func (in *PodDisruptionBudgetSpec) DeepCopy() *PodDisruptionBudgetSpec {
	if in == nil {
		return nil
	}
	out := new(PodDisruptionBudgetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleResult) DeepCopyInto(out *RuleResult) {
	*out = *in
	if in.HubPaths != nil {
		in, out := &in.HubPaths, &out.HubPaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SpokePaths != nil {
		in, out := &in.SpokePaths, &out.SpokePaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Lossless = in.Lossless
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Warnings != nil {
		in, out := &in.Warnings, &out.Warnings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleResult.
func (in *RuleResult) DeepCopy() *RuleResult {
	if in == nil {
		return nil
	}
	out := new(RuleResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalarToFieldsParams) DeepCopyInto(out *ScalarToFieldsParams) {
	*out = *in
	if in.SpokeFields != nil {
		in, out := &in.SpokeFields, &out.SpokeFields
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalarToFieldsParams.
func (in *ScalarToFieldsParams) DeepCopy() *ScalarToFieldsParams {
	if in == nil {
		return nil
	}
	out := new(ScalarToFieldsParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalarToObjectParams) DeepCopyInto(out *ScalarToObjectParams) {
	*out = *in
	if in.DefaultsForOtherKeys != nil {
		in, out := &in.DefaultsForOtherKeys, &out.DefaultsForOtherKeys
		*out = make(map[string]apiextensionsv1.JSON, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalarToObjectParams.
func (in *ScalarToObjectParams) DeepCopy() *ScalarToObjectParams {
	if in == nil {
		return nil
	}
	out := new(ScalarToObjectParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSpec) DeepCopyInto(out *ServiceSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSpec.
func (in *ServiceSpec) DeepCopy() *ServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SingletonArrayToObjectParams) DeepCopyInto(out *SingletonArrayToObjectParams) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SingletonArrayToObjectParams.
func (in *SingletonArrayToObjectParams) DeepCopy() *SingletonArrayToObjectParams {
	if in == nil {
		return nil
	}
	out := new(SingletonArrayToObjectParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpokeConversionStatus) DeepCopyInto(out *SpokeConversionStatus) {
	*out = *in
	out.Lossless = in.Lossless
	if in.FieldsUncoveredHub != nil {
		in, out := &in.FieldsUncoveredHub, &out.FieldsUncoveredHub
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FieldsUncoveredSpoke != nil {
		in, out := &in.FieldsUncoveredSpoke, &out.FieldsUncoveredSpoke
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RuleResults != nil {
		in, out := &in.RuleResults, &out.RuleResults
		*out = make([]RuleResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Warnings != nil {
		in, out := &in.Warnings, &out.Warnings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpokeConversionStatus.
func (in *SpokeConversionStatus) DeepCopy() *SpokeConversionStatus {
	if in == nil {
		return nil
	}
	out := new(SpokeConversionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpokeVersionRules) DeepCopyInto(out *SpokeVersionRules) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]ConversionRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpokeVersionRules.
func (in *SpokeVersionRules) DeepCopy() *SpokeVersionRules {
	if in == nil {
		return nil
	}
	out := new(SpokeVersionRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetCRDRef) DeepCopyInto(out *TargetCRDRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetCRDRef.
func (in *TargetCRDRef) DeepCopy() *TargetCRDRef {
	if in == nil {
		return nil
	}
	out := new(TargetCRDRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetXRDRef) DeepCopyInto(out *TargetXRDRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetXRDRef.
func (in *TargetXRDRef) DeepCopy() *TargetXRDRef {
	if in == nil {
		return nil
	}
	out := new(TargetXRDRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToMetadataParams) DeepCopyInto(out *ToMetadataParams) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToMetadataParams.
func (in *ToMetadataParams) DeepCopy() *ToMetadataParams {
	if in == nil {
		return nil
	}
	out := new(ToMetadataParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypeCoerceParams) DeepCopyInto(out *TypeCoerceParams) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypeCoerceParams.
func (in *TypeCoerceParams) DeepCopy() *TypeCoerceParams {
	if in == nil {
		return nil
	}
	out := new(TypeCoerceParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookServerRef) DeepCopyInto(out *WebhookServerRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookServerRef.
func (in *WebhookServerRef) DeepCopy() *WebhookServerRef {
	if in == nil {
		return nil
	}
	out := new(WebhookServerRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XRDConversionConfig) DeepCopyInto(out *XRDConversionConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XRDConversionConfig.
func (in *XRDConversionConfig) DeepCopy() *XRDConversionConfig {
	if in == nil {
		return nil
	}
	out := new(XRDConversionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XRDConversionConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XRDConversionConfigList) DeepCopyInto(out *XRDConversionConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]XRDConversionConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XRDConversionConfigList.
func (in *XRDConversionConfigList) DeepCopy() *XRDConversionConfigList {
	if in == nil {
		return nil
	}
	out := new(XRDConversionConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XRDConversionConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XRDConversionConfigSpec) DeepCopyInto(out *XRDConversionConfigSpec) {
	*out = *in
	out.TargetXRD = in.TargetXRD
	if in.Spokes != nil {
		in, out := &in.Spokes, &out.Spokes
		*out = make([]SpokeVersionRules, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.WebhookServerRef != nil {
		in, out := &in.WebhookServerRef, &out.WebhookServerRef
		*out = new(WebhookServerRef)
		**out = **in
	}
	if in.ConversionReviewVersions != nil {
		in, out := &in.ConversionReviewVersions, &out.ConversionReviewVersions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XRDConversionConfigSpec.
func (in *XRDConversionConfigSpec) DeepCopy() *XRDConversionConfigSpec {
	if in == nil {
		return nil
	}
	out := new(XRDConversionConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XRDConversionConfigStatus) DeepCopyInto(out *XRDConversionConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SpokeStatuses != nil {
		in, out := &in.SpokeStatuses, &out.SpokeStatuses
		*out = make([]SpokeConversionStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XRDConversionConfigStatus.
func (in *XRDConversionConfigStatus) DeepCopy() *XRDConversionConfigStatus {
	if in == nil {
		return nil
	}
	out := new(XRDConversionConfigStatus)
	in.DeepCopyInto(out)
	return out
}
