apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: xwidgets.example.org
spec:
  scope: Namespaced
  defaultCompositionRef:
    name: xwidgets-v3.example.org
  group: example.org
  names:
    kind: XWidget
    plural: xwidgets
  versions:
    - name: v3
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [name, capacity]
              properties:
                name:
                  type: string
                capacity:
                  type: string
            status:
              type: object
              properties:
                phase:
                  type: string
    - name: v2
      served: true
      referenceable: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [widgetName, capacity]
              properties:
                widgetName:
                  type: string
                capacity:
                  type: string
            status:
              type: object
              properties:
                phase:
                  type: string
