apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: conversion-configs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/TeraSky-OSS/declarative-conversion-operator
    targetRevision: main
    path: examples/gitops/configs
