apiVersion: terasky.com/v1alpha1
kind: XRDConversionConfig
metadata:
  name: xwidgets-conversion
spec:
  targetXRD:
    name: xwidgets.example.org
  hubVersion: v1
  spokes:
    - version: v2
      rules:
        - strategy: FieldRename
          fieldRename:
            hubPath: spec.size
            spokePath: spec.capacity
